<?xml version="1.0"?>
<robot name="ackrm_robot" 
  xmlns:xacro="http://ros.org/wiki/xacro">

  

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="chassis_length" value="0.22" />
  <xacro:property name="chassis_width" value="0.14" />
  <xacro:property name="chassis_heigth" value="0.03" />
  <xacro:property name="chassis_mass" value="${chassis_length*chassis_width*chassis_heigth*5000}" />
  <xacro:property name="wheel_radius" value="0.035" />
  <xacro:property name="wheel_length" value="0.03" />
  <xacro:property name="wheel_mass" value="${pi*wheel_radius*wheel_radius*wheel_length*500}" />
  <xacro:property name="virtual_wheel_radius" value="0.005" />
  <xacro:property name="virtual_wheel_length" value="0.001" />
  <xacro:property name="virtual_wheel_mass" value="0.001" />

  <xacro:include filename="wheel_macros.xacro" />


<link name="base_link">
</link>

<joint name="chassis_joint" type="fixed">
  <parent link="base_link"/>
  <child link="chassis_link"/>
  <origin xyz="0 0 0"/>    
</joint>

  <link name="chassis_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_heigth}" />
      </geometry>
      <material name="white" />
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_heigth}" />
      </geometry>
    </collision>

    <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_heigth}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>  
    
  </link>


  <link name="front_wheel_steering">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius-0.01}"/>
      </geometry>
      <material name="invisible"/>
    </visual>

    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius-0.01}">
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
    </xacro:inertial_cylinder>

    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
      <geometry>
          <cylinder radius="${wheel_radius-0.01}" length="${wheel_length}"/>
      </geometry>
    </collision>

  </link>

  <joint name="front_wheel_steering_joint" type="revolute">
    <parent link="chassis_link"/>
    <child link="front_wheel_steering"/>
    <origin xyz="${chassis_length/2+wheel_radius+0.01} 0 0" rpy="0 0 ${PI/2}"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${PI/4}" upper="${PI/4}" effort="100.0" velocity="0.0"/>
    <dynamics damping="0.03"/>
  </joint>

  <link name="front_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
    </xacro:inertial_cylinder>

    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
      <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>

  </link>

  <joint name="front_wheel_joint" type="continuous">
    <parent link="front_wheel_steering"/>
    <child link="front_wheel"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>"


  <link name="virtual_rear_wheel">
    
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${virtual_wheel_length}" radius="${virtual_wheel_radius}"/>
      </geometry>
      <material name="invisible"/>
    </visual>
    
    <xacro:inertial_cylinder mass="${virtual_wheel_mass}" length="${virtual_wheel_length}" radius="${virtual_wheel_radius}">
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
    </xacro:inertial_cylinder>

    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
      <geometry>
          <cylinder radius="${virtual_wheel_radius}" length="${virtual_wheel_length}"/>
      </geometry>
    </collision>

  </link>

  <joint name="virtual_rear_wheel_joint" type="continuous">
    <parent link="chassis_link"/>
    <child link="virtual_rear_wheel"/>
    <origin xyz="-${chassis_length/2-wheel_radius} 0 0" rpy="0 0 ${PI/2}"/>
    <axis xyz="1 0 0"/>
    <limit effort="100.0" velocity="100.0"/>
    <dynamics damping="0.03"/>
  </joint>

  <link name="right_rear_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
    </xacro:inertial_cylinder>

    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
      <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>
  </link>

  <joint name="right_rear_wheel_joint" type="fixed">
    <parent link="virtual_rear_wheel"/>
    <child link="right_rear_wheel"/>
    <origin xyz="${chassis_width/2+wheel_length/2+0.01} 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>

  <link name="left_rear_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
    </xacro:inertial_cylinder>

    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
      <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>
  </link>

  <joint name="left_rear_wheel_joint" type="fixed">
    <parent link="virtual_rear_wheel"/>
    <child link="left_rear_wheel"/>
    <origin xyz="-${chassis_width/2+wheel_length/2+0.01} 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>


</robot>