<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">   

    <xacro:property name="kinect_length" value="0.09" /> 
    <xacro:property name="kinect_heigth" value="0.03" /> 
    <xacro:property name="kinect_width" value="0.03" />
    <xacro:property name="kinect_mass" value="0.5" /> 
 

    <joint name="kinect_joint" type="fixed">
        <axis xyz="0 0 0" />
        <origin xyz="${chassis_length/2-kinect_width/2} 0 ${wheel_radius+kinect_heigth/2}" rpy="0 0 0"/>
        <parent link="chassis_link"/>
        <child link="kinect_link"/>
    </joint>
    
    <link name="kinect_link">
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
        <box size="${kinect_width} ${kinect_length} ${kinect_heigth}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
        <box size="${kinect_width} ${kinect_length} ${kinect_heigth}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${kinect_mass}" x="${kinect_width}" y="${kinect_length}" z="${kinect_heigth}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <link name="kinect_optical_link"/>
        <joint name="kinect_optical_joint" type="fixed">
        <parent link="kinect_link"/>
        <child link="kinect_optical_link"/>
        <origin xyz="0 0 0" rpy="-${PI/2} 0 -${PI/2}"/> 
    </joint>

    <gazebo reference="kinect_link">
        <material>Gazebo/Blue</material>
        <gravity>true</gravity>
    
        <sensor name="kinect_camera" type="depth">
            <update_rate>20</update_rate>
            <alwaysOn>true</alwaysOn>

            <camera name="kinect_ir">
                <horizontal_fov>1.047198</horizontal_fov>
                <image>
                    <width>1280</width>
                    <height>720</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>16</far>
                </clip>

                <distortion>
                    <k1>0.0</k1>
                    <k2>0.0</k2>
                    <k3>0.0</k3>
                    <p1>0.0</p1>
                    <p2>0.0</p2>
                    <center>0.5 0.5</center>
                </distortion>
            </camera>

            <plugin name="camera_plugin" filename="libgazebo_ros_camera.so">
                <camera_name>kinect_ir</camera_name>
                <frame_name>kinect_optical_link</frame_name>
                
                <hack_baseline>0.07</hack_baseline>
                <min_depth>0.001</min_depth>
            </plugin>
        </sensor>
    </gazebo>
</robot>