joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.2
    autorepeat_rate: 200.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 2.5

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 2.5

    enable_button: 9
    require_enable_button: true

    