twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.005
        priority: 10
      joystick  : 
        topic   : cmd_vel_joy
        timeout : 0.005
        priority: 50
      AEB  : 
        topic   : cmd_vel_aeb
        timeout : 0.005
        priority: 100